import 'bootstrap';
import './css/app.scss';
import { services } from './modules/services';
import { about } from './modules/about';
import { features } from './modules/features';
import { footer } from './modules/footer';
import { nav } from './modules/nav';
import { hero } from './modules/hero';

const serviceSection = document.getElementById('services');
const aboutSection = document.getElementById('about');
const featureSection = document.getElementById('features');
const footerSection = document.querySelector('.footer');
const heroSection = document.getElementById('home');
const navbar = document.querySelector('.navbar');
serviceSection.innerHTML = services;
aboutSection.innerHTML = about;
featureSection.innerHTML = features;
footerSection.innerHTML = footer;
navbar.innerHTML = nav;
navbar.innerHTML = nav;
heroSection.innerHTML = hero;